### ISSUE TITLE
System.Management.Automation.RuntimeException: Method invocation failed because [System.Management.Automation.ErrorRecord] doesn't contain a method named 'ForEach'.

### ISSUE THREAD

**Issue by Tankatronic** [kirkone/vsts-dnx-tasks#23]
I have been unable to build a web package using the DNX Tasks. It seems to actually compile my project fine but there seems to be a problem with the Powershell script. I changed the .ForEach method call to a foreach loop and it worked fine after that. Am I missing a module or something?
```
******************************************************************************
Starting: Build Web Package: [ProjectName]
******************************************************************************
Preparing task execution handler.
Executing the powershell script: C:\agent\_work\_tasks\DNX.Tasks.BuildWebPackage_18e7af2f-a100-4868-9c88-bb3a07b3b3be\0.1.23\BuildWebPackage.ps1
Parameter Values:
    ProjectName = [ProjectName]
    BuildConfiguration = Release
    OutputFolder = C:\agent\_work\6\a
    PublishSource = false
    WorkingFolder = C:\agent\_work\6\s\Server\src\
    SourceFolder = 
    SkipDotNetInstall = true
 
    1 Projects to build
 
dotnet restore for:
    ".\[ProjectName]"
 
    log  : Restoring packages for C:\agent\_work\6\s\Server\src\[ProjectName]\project.json...
    log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in C:\agent\_work\6\s\Server\src\[ProjectName]\project.json...
    log  : Lock file has not changed. Skipping lock file write. Path: C:\agent\_work\6\s\Server\src\[ProjectName]\project.lock.json
    log  : .\[ProjectName]\project.json
    log  : Restore completed in 2311ms.
    Restore done.
 
dotnet build for:
    ".\[ProjectName]"
 
    Project [ProjectName2] (.NETFramework,Version=v4.5.1) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
    Compiling [ProjectName2] for .NETFramework,Version=v4.5.1
    
    Compilation succeeded.
        3 Warning(s)
        0 Error(s)
    
    Time elapsed 00:00:01.8644790
    Project [ProjectName] (.NETFramework,Version=v4.5.1) will be compiled because dependencies changed
    Compiling [ProjectName] for .NETFramework,Version=v4.5.1
    
    Compilation succeeded.
        0 Warning(s)
        0 Error(s)
    
    Time elapsed 00:00:02.3561909
     (The compilation time can be improved. Run "dotnet build --build-profile" for more information)
    
    Warnings:
 
System.Management.Automation.RuntimeException: Method invocation failed because [System.Management.Automation.ErrorRecord] doesn't contain a method named 'ForEach'.
   at System.Management.Automation.EnumerableOps.MethodInvokerWorker(CallSite invokeMemberSite, IEnumerator enumerator, Object[] args, ExecutionContext context, ArrayList result, Boolean& foundMethod)
   at System.Management.Automation.EnumerableOps.MethodInvoker(PSInvokeMemberBinder binder, Type delegateType, IEnumerator enumerator, Object[] args, Type typeForMessage)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
 
    Build done.
 
dotnet publish for:
    ".\[ProjectName]"
 
    Publishing [ProjectName] for .NETFramework,Version=v4.5.1/win7-x64
    Configuring the following project for use with IIS: 'C:\agent\_work\6\a\[ProjectName]'
    Updating web.config at 'C:\agent\_work\6\a\[ProjectName]\web.config'
    Configuring project completed successfully
    publish: Published to C:\agent\_work\6\a\[ProjectName]
    Published 1/1 projects successfully
 
    Publish done for: .\[ProjectName]
 
PowerShell script completed with 1 errors.
******************************************************************************
Finishing: Build Web Package: [ProjectName]
******************************************************************************
```

**Comment by kirkone** [comment]
Hi,

I am not sure why there are two compile steps. One with three warnings and one with zero warnings.
I will have a look into this and try to reproduce this.
Sorry fir the trouble.

**Comment by Tankatronic** [comment]
The second step is a another dependent project in the solution. I probably should have named it [SecondProjectName] or something. I can edit it.

**Comment by kirkone** [comment]
Is this build running on a hosted controller?

Can you show what you have changed when it is running well?

**Comment by kirkone** [comment]
I think .ForEach is introduced with PowerShell 4.0. Maybe this is the problem here.

**Comment by Tankatronic** [comment]
I made changes to these following sets of lines. This is what I changed it to, before it was just $buildWarnings.ForEach({...}) for example

```
if ($buildWarnings.Count -gt 0)
    {
        Write-Host "    Warnings:`n`r "
		foreach($warning in $buildWarnings)
		{
			if ($warning -ne [string]::IsNullOrWhiteSpace($warning))
            {
                Write-Host "##vso[task.logissue type=warning;]Warning: $warning"
            }
		} 
        Write-Host " `n`r "
    }

    if ($buildErrors.Count -gt 0)
    {
        Write-Host "    Errors:`n`r "
        foreach($error in $buildErrors)
		{
            if ($error -ne [string]::IsNullOrWhiteSpace($error) -and
                -not ($error -like "*dotnet-compile.rsp returned Exit Code 1*"))
            {
                Write-Host "##vso[task.logissue type=error;]Error: $error"
            }
        }
        Write-Host "##vso[task.complete result=Failed;]Build Failed!"
        Write-Host "    Build Failed!`n`r "
        Write-Host " "

        exit 1
    }

...

        if ($publishWarnings.Count -gt 0)
        {
            Write-Host "    Warnings:`n`r "
		foreach($warning in $publishWarnings)
		{
			if ($warning -ne [string]::IsNullOrWhiteSpace($warning))
                       {
                            Write-Host "##vso[task.logissue type=warning;]Warning: $warning"
                       }
                }
            Write-Host " `n`r "
        }

        if ($publishErrors.Count -gt 0)
        {
            Write-Host "    Errors:`n`r "
			foreach($error in $publishErrors)
			{
				if ($error -ne [string]::IsNullOrWhiteSpace($error))
                {
                    Write-Host "##vso[task.logissue type=error;]Error: $error"
                }
            }
            Write-Host " `n`r "
        

            Write-Host "##vso[task.complete result=Failed;]Publish Failed!"
            Write-Host "    Publish Failed!`n`r "
            Write-Host " "

            exit 1
        }

```

**Comment by kirkone** [comment]
Ah, this looks much better an this should be compatible with PowerShell 3 also.
Do you want to provide me a Pull request for this?
I will update the package in about 8h.

Thank for pointing this out!

**Comment by Tankatronic** [comment]
Sure thing. I'll get the PR up in a bit.

**Comment by kirkone** [comment]
Published the new package. Give it a try.

Thanks for your help!
